apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: itm-ingress
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-buffers-number: "8"
    nginx.ingress.kubernetes.io/proxy-buffer-size: "32k"
    nginx.ingress.kubernetes.io/server-snippet: |
      large_client_header_buffers 4 128k;
      client_header_buffer_size 64k;
    nginx.org/client-max-body-size: "50m"
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - zhhen-dev.itm.dev
    - zhhen-devservice.itm.dev
    - zhhen-dev-reports.itm.dev
    - crudapi.itm.dev
    - crud.itm.dev
    secretName: itm-tls
  rules:
  - host: zhhen-dev.itm.dev
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: web
              port:
                number: 80
  - host: zhhen-devservice.itm.dev
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: gateway
              port:
                number: 8080
  - host: zhhen-dev-reports.itm.dev
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: metabase
              port:
                number: 3000
  - host: crudapi.itm.dev
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: dotnet-mongodb
              port:
                number: 8888
  - host: crud.itm.dev
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: react-task
              port:
                number: 5173