apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-buffers-number: "8"
    nginx.ingress.kubernetes.io/proxy-buffer-size: "32k"
    nginx.org/client-max-body-size: "50m"
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - crud2.xiluo.net
    - crudapi.xiluo.net
    secretName: tls-secret
  rules:
  - host: crud2.xiluo.net
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: react-frontend
              port:
                number: 5173
  - host: crudapi.xiluo.net
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: dotnet-backend
              port:
                number: 8888