apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-task
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-task
  template:
    metadata:
      labels:
        app: react-task
    spec:
      containers:
        - name: react-task
          image: node:20-alpine
          imagePullPolicy: IfNotPresent
          workingDir: /app
          env:
            - name: NODE_ENV
              value: "development"
            - name: CHOKIDAR_USEPOLLING
              value: "true"
          command: ["sh","-c"]
          args: ["npm ci && npm run dev -- --host 0.0.0.0 --port 5173"]
          ports:
            - containerPort: 5173
          readinessProbe:
            tcpSocket:
              port: 5173
            initialDelaySeconds: 3
            periodSeconds: 5
          livenessProbe:
            tcpSocket:
              port: 5173
            initialDelaySeconds: 10
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: react-task
spec:
  selector:
    app: react-task
  ports:
    - port: 5173
      targetPort: 5173
      nodePort: 31573
  type: NodePort


